#!/usr/bin/env node
/* build-index.mjs — regenerates index.html, shaketoshake.css, spotlight-tpl.js from meettomeet.html
 *   + index-extras.{js,css} + index-s2s.{js,css}.
 * NOTE: index.html / shaketoshake.css / spotlight-tpl.js ARE git-tracked (full artifacts, NOT a stub) and
 *   Netlify deploys them verbatim (netlify.toml publish="."; no build command). They are NOT regenerated at
 *   deploy time, so you MUST re-run `node build-index.mjs` and commit the result whenever any source
 *   (meettomeet.html or index-extras.* / index-s2s.*) changes — otherwise the live site goes stale.
 * Freshness gate (optional): `node build-index.mjs && git diff --exit-code -- index.html shaketoshake.css spotlight-tpl.js`.
 */
import fs from 'fs';

const SRC = 'meettomeet.html';
const log = [];
let h = fs.readFileSync(SRC, 'utf8');
const srcLines = h.split('\n').length;

// 1. extract main app CSS (FIRST attribute-less <style> block) and externalize it
const m = h.match(/<style>([\s\S]*?)<\/style>/);
if (!m) { console.error('FATAL: main <style> block not found in ' + SRC); process.exit(1); }
const baseCss = m[1].replace(/^\n/, '');
h = h.replace(/<style>[\s\S]*?<\/style>/, '<link rel="stylesheet" href="shaketoshake.css">');
log.push('CSS externalized: ' + baseCss.length + ' chars -> shaketoshake.css');

// 2. head fixes
const vpNew = '<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">';
const hadVp = /<meta name="viewport"[^>]*>/.test(h);
h = h.replace(/<meta name="viewport"[^>]*>/, vpNew);
log.push('viewport: ' + (hadVp ? 'set to spec' : 'NOT FOUND'));
const hadMan = h.includes('href="manifest.webmanifest"');
h = h.replace('<link rel="manifest" href="manifest.webmanifest">', '<link rel="manifest" href="index.webmanifest">');
log.push('manifest: ' + (hadMan ? '-> index.webmanifest' : 'NOT FOUND'));
h = h.replace(/href="\/(icon-512|icon-source)\.png"/g, 'href="$1.png"');

// 3. unify root-absolute local src -> relative
const absN = (h.match(/ src="\/(?!\/)/g) || []).length;
h = h.replace(/ src="\/(?!\/)/g, ' src="');
log.push('root-absolute src unified to relative: ' + absN);

// 4. inject the extras script right after app.js
const anchor = '<script src="app.js"></script>';
if (!h.includes(anchor)) { console.error('FATAL: app.js script tag not found'); process.exit(1); }
if (!h.includes('index-extras.js')) {
  h = h.replace(anchor, anchor + '\n<script src="index-extras.js"></script>\n<script src="index-s2s.js"></script>');
}
log.push('index-extras.js + index-s2s.js injected after app.js');

// 5. spotTpl（スポットライト検索テンプレ）を外出し:
//    インラインの <script type="text/html" id="spotTpl"> は入れ子の </script> を <\/script> でエスケープしており、
//    VS Code/TSサーバがそれを誤読してテンプレ内CSSをJSとして1000+の誤検知を出す。ブラウザでは正しく動く。
//    → テンプレ文字列を spotlight-tpl.js(クリーンなJS文字列)へ外出しし、index.html側は空タグ＋パース時に再注入。挙動は同一。
const spotRe = /<script type="text\/html" id="spotTpl">([\s\S]*?)<\/script>/;
const spotM = h.match(spotRe);
if (spotM) {
  fs.writeFileSync('spotlight-tpl.js', '/* auto-generated by build-index.mjs — 旧 #spotTpl インラインテンプレを文字列化（VS Code誤検知回避）。編集は meettomeet.html 側で。 */\nwindow.__SPOTTPL=' + JSON.stringify(spotM[1]) + ';\n');
  h = h.replace(spotRe, '<script src="spotlight-tpl.js"></script>\n<script type="text/html" id="spotTpl"></script>\n<script>try{document.getElementById("spotTpl").textContent=window.__SPOTTPL||"";}catch(e){}</script>');
  log.push('spotTpl externalized -> spotlight-tpl.js (' + spotM[1].length + ' chars; index.html now parser-clean)');
} else {
  log.push('spotTpl: NOT FOUND (skip)');
}

// write outputs
const readIf = f => fs.existsSync(f) ? '\n\n/* ===== ' + f + ' ===== */\n' + fs.readFileSync(f, 'utf8') : '';
const extrasCss = readIf('index-extras.css') + readIf('index-s2s.css');
fs.writeFileSync('shaketoshake.css', baseCss + extrasCss);
// NOTE: index.html は globe-chat（メインチャット）に置き換え済み。旧appのビルド出力は
// classic.html に向ける（index.html を上書きして globe-chat を消さないため）。
fs.writeFileSync('classic.html', h);

log.push('OUTPUT classic.html: ' + h.split('\n').length + ' lines (' + h.length + ' chars), from meettomeet.html ' + srcLines + ' lines');
console.log(log.map(l => '  • ' + l).join('\n'));
